# Generated by Django 2.2 on 2019-04-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Цвет глаз',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
