# Generated by Django 2.2 on 2019-04-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0003_auto_20190407_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Цвет глаз',
            new_name='eye',
        ),
    ]
