# Generated by Django 2.2 on 2019-04-06 10:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('title', models.TextField(default='Russia', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EyeColor',
            fields=[
                ('title', models.TextField(default='Russia', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
