# Generated by Django 2.2 on 2019-04-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0002_user_цвет глаз'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Цвет глаз',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
