# Generated by Django 2.2 on 2019-04-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0004_auto_20190407_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
